server:
  port: 10001
  ssl:
    key-store: classpath:weather.p12
    key-store-password: kevin123
    key-store-type: PKCS12
weather-api:
  ribbon:
    listOfServers: http://api.seniverse.com
  seniverse:
    api-key: cle0eeznspa9x37a
    location: wuhan
ip-api:
  ribbon:
    listOfServers: http://ip.taobao.com
logging:
  config: classpath:log4j2.xml
spring:
  jackson:
    default-property-inclusion: non_null

