server:
  port: 10001
weather-api:
  ribbon:
    listOfServers: http://api.seniverse.com
  seniverse:
    api-key: cle0eeznspa9x37a
    location: wuhan
spring:
  jackson:
    default-property-inclusion: non_null
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
        bindings:
          currentWeather:
            destination: currentWeather
            content-type: text/plain

