server:
  port: 10001
weather-api:
  ribbon:
    listOfServers: http://api.seniverse.com
  seniverse:
    api-key: cle0eeznspa9x37a
    location: wuhan
spring:
  jackson:
    default-property-inclusion: non_null
  cloud:
    stream:
      bindings:
        currentWeather:
          binder: kafka
          destination: currentWeather
          content-type: text/plain
        event_rabbit_in:
          binder: rabbit
          destination: test_exch
          group: test_group
      binders:
        kafka:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: 127.0.0.1:9092
                      zkNodes: 127.0.0.1:2181
                      auto-add-partitions: true
                      auto-create-topics: true
                      min-partition-count: 1
        rabbit:
          type: rabbit
          environment:
            spring:
              cloud:
                stream:
                  rabbitmq:
                    addresses: localhost:5672
      default-binder: rabbit

